flowchart LR

Tutor([Tutor])
Cuidador([Cuidador])

subgraph TapatApp
  R[Registrarse]
  L[Iniciar sesión]
  GN[Gestionar niño]
  VN[Ver niño]
  GT[Gestionar tareas]
  AT[Asignar tareas]
  VT[Ver tareas]
  CT[Completar tareas]
end

Tutor --> R
Tutor --> L
Tutor --> GN
Tutor --> GT
Tutor --> AT
Tutor --> VT

Cuidador --> L
Cuidador --> VN
Cuidador --> VT
Cuidador --> CT

GT -. incluye .-> AT
VT -. extiende .-> CT